### ISSUE TITLE
Short-range-Bluetooth

### ISSUE THREAD

**Issue by ghost** [GSoft-Goldsmiths/iLost-Back-end#2]
All work related to making the tracker work at short range (less than 30 meters)

**Comment by mpeco001** [comment]
We can use an Estimote iBeacon to estimate the short range that communicate with Rapsberry Pi tracker , so that if the tracker do not receive signals from the Beacon means that you are not in rage with your tracker and it pop up a notification / sms with link .

Got to use Node-Bleacon, a Node.js library for creating, discovering, and configuring iBeacons.

**Comment by ghost** [comment]
http://www.espruino.com/Puck.js

I have just brought one on the pucks (it uses javascript too). when it delivers, im going to try and get this to work with the raspberry pi, it always best to try as many options for the bluetooth beacons.

**Comment by ghost** [comment]
making good progress on the puck.js, 30% there in order to make a short range work

**Comment by ghost** [comment]
ive evaluated the puck.js. ive managed to break it many times now. I can conclude that it is not suitable for our short-range capability (i've spent a lot of money and time on it).

We now need to focus on getting the estimotes to work.

**Comment by ghost** [comment]
I think this feature may be dropped. we underestimated the complexity of Bluetooth as do many developers.

**Comment by ghost** [comment]
At this stage the Bluetooth functionality is discarded. I've already done a good report in the design section of all our attempts and workarounds. Ideally we would need experienced Developers who have successfully worked with Bluetooth.
